### ISSUE TITLE
format date-time generates invalid identifier

### ISSUE THREAD

**Issue by kontsaki** [oxidecomputer/progenitor#749] opened 2024-03-26 17:15 UTC
Hello,

progenitor from main

a property like the following

```
              "created_at": {
                "type": "string",
                "format": "date-time",
                "readOnly": true,
                "default": "1970-01-01T00:00:00Z"
              }
```

results in

```
error: proc macro panicked
 --> src/main.rs:5:1
  |
5 | / generate_api!(
6 | |     spec = "../openapi_spec.json",
7 | |     derives = [schemars::JsonSchema],
8 | | );
  | |_^
  |
  = help: message: `"DateTime<chrono"` is not a valid identifier
```

**Comment by ahl** [comment] 2024-03-28 22:57
Great bug! Thanks for finding it.

It turns out to be an issue in typify. I've put the details here: https://github.com/oxidecomputer/typify/issues/539

Are you using progenitor from a git reference or the released version on crates.io? If the latter, I can get a new release out.

**Comment by kontsaki** [comment] 2024-03-29 16:02
Thank you for fixing this. I tried both from git main branch and the released crate. I don't have an immediate need for a crate release so it's up to you. 

I am trying to make progenitor work with the schema generated by rocket_okapi and it seems they are some incompatibilities. I will try to investigate further.

**Comment by ahl** [comment] 2024-03-29 16:29
Thanks for taking a look. Can you share the schema? It's not surprising to me that there might be constructions that we haven't encountered before.

**Comment by ahl** [comment] 2024-04-10 21:29
That typify bug has a minimal reproduction. I'm closing this as it should work in progenitor now that we've synced up with the typify git dependency.

**Closed by ahl** 2024-04-10 21:29 UTC
